### PR TITLE
Use correct logging method

### PR DESCRIPTION
**Pull request by Takuto88**
Fixes an issue introduced with 2af8284493c4631b5584da4a976d1e8534cba9b8
where suddenly errors like these appeard in my systemd log:

```
gnome-shell[5070]: JS ERROR: Exception in callback for signal: icon: TypeError: Util.Logger.fatal is not a function
_getIconInfo@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:408:21
_cacheOrCreateIconByName@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:334:27
_updateIcon@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:513:27
_emit@resource:///org/gnome/gjs/modules/signals.js:135:27
_onPropertiesChanged/<@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:17
_onPropertiesChanged@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:208:9
refreshPropertyOnProxy/<@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:42:37
```

I also changed the log level to debug because this is not critical and only noisy
logging IMHO. Critical / fatal errors should lead to program
termination which is not the case here.

### CODE REVIEW

**Comment by terencode** [comment]
Duplicate of #206 ?

**Comment by Takuto88** [comment]
It aims to fix the same issue yes. In contrast to the other one I also took the liberty to switch this to a `debug()` call because I don't think this is critical. Now the project maintainer can choose if he agrees with me. If not I won't be offended :wink:

**Comment by terencode** [comment]
Ah ok I see, thanks for clarifying.

**Comment by 3v1n0** [comment]
Thanks, I would keep this as a warning though, so will change this again in a further commit.

Thaks

**Comment by Takuto88** [comment]
Sure no biggie. Thanks for considering 🙂
