### ISSUE TITLE
Telegram and Nextcloud icons not showing on Wayland

### ISSUE THREAD

**Issue by Razer0123** [ubuntu/gnome-shell-extension-appindicator#372]
Not sure what is causing the issue, but icons are not showing on Wayland

Running F37, with v46

**Comment by supremesyntax** [comment]
Don't know if this is the same bug but for me no icons are displayed after update to v46.

journalctl says:

...
JS ERROR: TypeError: domain.replaceAll is not a function
...
Unable to connect to the Notification Watcher: GDBus.Error:org.gnome.gjs.JSError.ValueError: domain.replaceAll is not a function
...

I am getting this a few times un Ubuntu 20.04, GNOME Shell 3.36.9, i guess it is repeating for every app/icon that initializes.

**Comment by 3v1n0** [comment]
Duplicate of #374
