### ISSUE TITLE
Vorta's menu does not appears

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-extension-appindicator#418]
1. left click on Vorta's icon
2. a menu must appear, but it's not

no issue with v52

[gnomeshell_log.txt](https://github.com/ubuntu/gnome-shell-extension-appindicator/files/10973256/gnomeshell_log.txt)

AppIndicator 53
Gnome shell 3.38.5
Debian 11 stable
Vorta 0.7.5-1 from debian repository

**Comment by pranshugaba** [comment]
Same issue with Dropbox icon. Menu does not appear on click in v53. No issues in v52.

If I disable and enable the extension, then the menu appears on click. However, I need to do this after every reboot.

**Comment by 3v1n0** [comment]
Please provide shell logs and if possible try to `git bisect` to figure out which commit is the guilty one (I think could be https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/f57dbd5792a93fb28b6145d629e527b194fb6ab3 but I can't reproduce the issue myself)

**Comment by ztefn** [comment]
I can report that in v53 for Haguichi [indicator menu](https://github.com/ztefn/haguichi/blob/master/src/indicator-menu.vala) items do not show up again after being hidden ("connect/disconnect" menu items are hidden or shown depending on state).

Also disabled (insensitive) menu items are not enabled again when state changes ("join/create network" menu items are disabled when disconnected and should be re-enabled when connection is established).

> I think could be [f57dbd5](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/f57dbd5792a93fb28b6145d629e527b194fb6ab3)

That sounds very much related.

**Comment by JDaance** [comment]
Same for me with Dropbox, enabling and disabling makes it work :+1: 

I cant offer much help, but thanks for maintaining this extension :pray: !

**Comment by ztefn** [comment]
> Please provide shell logs and if possible try to `git bisect` to figure out which commit is the guilty one (I think could be [f57dbd5](https://github.com/ubuntu/gnome-shell-extension-appindicator/commit/f57dbd5792a93fb28b6145d629e527b194fb6ab3) but I can't reproduce the issue myself)

@3v1n0 Git bisect confirmed the quilty commit:

```
f57dbd5792a93fb28b6145d629e527b194fb6ab3 is the first bad commit
commit f57dbd5792a93fb28b6145d629e527b194fb6ab3
Author: Marco Trevisan (Treviño) <mail@3v1n0.net>
Date:   Fri Mar 10 05:57:43 2023 +0100

    dbusMenu: Do not update menu items while the menu is closed
    
    Ignore any update request when an indicator is not showing, there's no point
    to update the menu items at all, until we're opened again

 dbusMenu.js | 79 ++++++++++++++++++++++++++++++++++++++++++++++++-------------
 1 file changed, 62 insertions(+), 17 deletions(-)
```
There nothing reported in the system logs except for an icon update issue:

```
JS ERROR: haguichi unable to update icon: TypeError: oldIcon.equals is not a function
                                                 add@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/iconCache.js:55:34
                                                 _cacheOrCreateIconByName@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.j>
                                                 async*_createIcon@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1552:>
                                                 _createAndSetIcon@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1512:>
                                                 _updateIconByType@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1504:>
                                                 _updateIcon@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1581:24
                                                 _invalidateIcon@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:1636:14
                                                 _invalidateIconWhenFullyReady@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndica>
                                                 async*_init/<@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:935:24
                                                 _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                                 _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                                 reset@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:710:14
                                                 _ensureItemRegistered@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusNotifierWat>
                                                 RegisterStatusNotifierItemAsync@/home/stephen/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/statusN>
                                                 _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
                                                 _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
```

**Comment by dantheperson** [comment]
same here with dropbox.

turning 'AppIndicator and KStatusNotifierItem Support' off in the gnome extensions controlpanel, and then back on, got the dropbox item to start display the menu.
